apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: llm-d-kserve
    releaseName: gpt-oss-20b
    namespace: llm-d-example
    version: 0.2.2
    repo: https://redhat-ai-services.github.io/helm-charts/
    valuesFile: values.yaml
