apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-d-example

helmCharts:
- name: llm-d-kserve
  releaseName: gpt-oss-20b
  version: 0.1.0
  repo: https://redhat-ai-services.github.io/helm-charts/
  valuesFile: values.yaml
