hook:
  pre:
    image:
      repository: quay.io/cloud-architecture-workshop/wait-for-routes-job
      pullPolicy: IfNotPresent
      tag: "d41c5da-native"
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    argocd:
      enabled: true
      syncwave: "-1"

  post:
    image:
      repository: quay.io/cloud-architecture-workshop/trigger-pipelines-job
      pullPolicy: IfNotPresent
      tag: "7e399ca"
    podSecurityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    argocd:
      enabled: true
      syncwave: "1"

loop:
  count: 1
