chat_generation:
  service:
    hostname: granite-guardrails-hf-hap.apps.cluster-6vvfv.6vvfv.sandbox606.opentlc.com 
    port: 443
detectors:
  hap:
    type: text_contents
    service:
      hostname: granite-guardian-predictor.guardrails-hf-hap.svc.cluster.local
      port: 8000
    chunker_id: whole_doc_chunker
    default_threshold: 0.5
