apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-agent-mcp

helmCharts:
- name: kubernetes-mcp
  releaseName: kubernetes-mcp
  version: 0.1.2
  repo: https://redhat-ai-services.github.io/helm-charts/
  valuesFile: values.yaml
