apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'tech-preview-v0.1'
    target:
      kind: Subscription
      name: openshift-external-secrets-operator
