apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ include "argocd-appgenerator.fullname" . }}
  labels:
    rhoai-example-component: argocd-appgenerator
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - {{ .Values.repoURL }}
