---
apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: {{ .Values.apimanager.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    {{- include "3scale.labels" . | nindent 4 }}
spec:
  wildcardDomain: {{ .Values.clusterDomainUrl }}
  tenantName: {{ .Values.apimanager.tenantName }}
  resourceRequirementsEnabled: false
  system:
    fileStorage:
      {{ if .Values.apimanager.storageClassName -}}
      persistentVolumeClaim:
        storageClassName: {{ .Values.apimanager.storageClassName }}
      {{- else -}}
      simpleStorageService:
        configurationSecretRef:
          name: minio-s3-auth
      {{- end }}
  apicast:
    stagingSpec:
      labels:
        {{- include "3scale.labels" . | nindent 8 }}
  {{ if .Values.apimanager.llmMetrics }}
      customPolicies:
        - name: {{ .Values.apimanager.llmMetrics.name }}
          version: "{{ .Values.apimanager.llmMetrics.version }}"
          secretRef:
             name: {{ .Values.apimanager.llmMetrics.name }}
  {{- end }}
    productionSpec:
      labels:
        {{- include "3scale.labels" . | nindent 8 }}
  {{ if .Values.apimanager.llmMetrics }}
      customPolicies:
        - name: {{ .Values.apimanager.llmMetrics.name }}
          version: "{{ .Values.apimanager.llmMetrics.version }}"
          secretRef:
             name: {{ .Values.apimanager.llmMetrics.name }}
  {{- end }}
