---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  annotations:
    openshift.io/description: "Red Hat Integration - 3scale"
    openshift.io/display-name: "3scale"
  labels:
    {{- include "3scale.labels" . | nindent 4 }}
