{{- range $.Values.apis }}
{{- if eq (dig "deployment" "apicastHosted" "authentication" "oidc" "issuerType" "" .) "keycloak" }}
{{- $keycloakName := (dig "deployment" "apicastHosted" "authentication" "oidc" "issuerType" "issuerEndpointRef" "name" "" .)}}
{{- if $keycloakName }}
{{- $keycloakData := (dig "keycloaks" $keycloakName  "" $.Values) }}
{{- if $keycloakData }}
---
apiVersion: v1
kind: Secret
metadata: 
  name: '{{ $keycloakName }}'
  namespace: '{{ $.Values.namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  issuerEndpoint: '{{ (printf "https://%s:%s@rh-sso.rh-sso.%s/auth/realms/%s" $keycloakData.clientId $keycloakData.clientSecret $.Values.apimanager.wildcardDomain $keycloakData.realm) | b64enc }}'
{{- end }}
{{- end }}
{{- end }}
{{- end }}
