{{ if not .Values.apimanager.storageClassName -}}
kind: Secret
apiVersion: v1
metadata:
  name: minio-s3-auth
  namespace: '{{ .Values.namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    apimanager.apps.3scale.net/watched-by: apimanager
    {{- include "3scale.labels" . | nindent 4 }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: '{{ .Values.AsMap | dig "minio" "accessKey" "minio" | b64enc }}'
  AWS_SECRET_ACCESS_KEY: '{{ .Values.AsMap | dig "minio" "secretKey" "minio123"| b64enc }}'
  AWS_BUCKET: '{{ .Values.AsMap | dig "minio" "bucket" "3scale-maas" | b64enc }}'
  AWS_REGION: '{{ "us-east-1" | b64enc }}'
  AWS_HOSTNAME: '{{ .Values.AsMap | dig "minio" "host" "minio.minio.svc:9000" | b64enc }}'
  AWS_PROTOCOL: '{{ "HTTP" | b64enc }}'
  AWS_PATH_STYLE: '{{ "true" | b64enc }}'
{{- end }}
