{{ if .Values.apimanager.llmMetrics -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apimanager.llmMetrics.name }}
  namespace: {{ .Values.namespace }}
  labels:
    apimanager.apps.3scale.net/watched-by: apimanager
    {{- include "3scale.labels" . | nindent 4 }}
data:
  apicast-policy.json: '{{ .Files.Get "llm_metrics_policy/apicast-policy.json" | b64enc }}'
  custom_metrics.lua: '{{ .Files.Get "llm_metrics_policy/custom_metrics.lua" | b64enc }}'
  init.lua: '{{ .Files.Get "llm_metrics_policy/init.lua" | b64enc }}'
  llm.lua: '{{ .Files.Get "llm_metrics_policy/llm.lua" | b64enc }}'
  portal_client.lua: '{{ .Files.Get "llm_metrics_policy/portal_client.lua" | b64enc }}'
  response.lua: '{{ .Files.Get "llm_metrics_policy/response.lua" | b64enc }}'
{{- end }}
