apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: '{{ .Values.namespace | default "redhat-sso" }}'
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    rhoai-example: maas
    rhoai-example-component: redhat-sso-instance
spec:
  selector:
    app: postgres-db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
